//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedBox.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.UserEvents = new HashSet<UserEvent>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public bool Archived { get; set; }
    
        public virtual ICollection<UserEvent> UserEvents { get; set; }
    }
}
