//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedBox.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string UserId { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> IsEmployed { get; set; }
        public Nullable<bool> CanBeVotedEOM { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
